### ISSUE TITLE
Missing CUBA and corrections needed for the cuba.yml and simphony_metadata.yml

### ISSUE THREAD

**Issue by kitchoi** [simphony/simphony-metadata#18]
I had to make these changes to the yaml files in order to pass tests in #17 locally
cuba.yml:
https://gist.github.com/kitchoi/1815eeef45356a2eac0551845eea837c

simphony_metadata.yml
https://gist.github.com/kitchoi/aee20170f5d5690c95c153272a669a26

@ahashibon, @tuopuu  Can you have a look please?

**Comment by kitchoi** [comment]
This one probably also needs fixing: Can't assign a single value to something with `shape = (2)`, either we get rid of `default`, or modify the `default`, or the `shape` for this one.

```
  SURFACE_TENSION_RELATION:
    parent: CUBA.MATERIAL_RELATION
    definition: Surface tension relation between two fluids
    models: [CUBA.CONTINUUM]
    CUBA.SURFACE_TENSION:
      default: 0.07
      scope: CUBA.USER
      shape: (2)
```
