### ISSUE TITLE
CUBA.DATA should be defined

### ISSUE THREAD

**Issue by mehdisadeghi** [simphony/simphony-metadata#21]
CUBA.DATA is missing from metadata definition. We can define it this way:

```
CUBA.DATA:
  definition: A generic container
  parent: CUBA.CUDS_COMPONENT
```

However it is still incomplete, how we should show its container nature (dict, shape)?

One can use it:

```
CUBA.EXAMPLE:
    definition: an example structure
    parent: CUBA.CUDS_COMPONENT
    CUBA.DATA:
      shape: (10)
```

everything would be much easier if we could write:

```
CUBA.EXAMPLE:
    definition: an example structure
    parent: CUBA.CUDS_COMPONENT
    CUBA.CUDS_COMPONENT:
      name: data
      shape: (10)
```

Please comment. @ahashibon @kitchoi
