### ISSUE TITLE
change "category" to concept

### ISSUE THREAD

**Issue by ahashibon** [simphony/simphony-metadata#69]
to make the "definition" consistent with the materials modelling ontology, a "category" shold be replaced with concept and used consistently. e.g., 

 ```
 INTERATOMIC_POTENTIAL:
    definition: Interatomic Potentials Category  --> concept
    parent: CUBA.MATERIAL_RELATION
    models: [CUBA.ATOMISTIC]

```
