### ISSUE TITLE
Meaning of empty variables?

### ISSUE THREAD

**Issue by stefanoborini** [simphony/simphony-metadata#91]
What is the intended meaning of something like:

```
  MODEL_EQUATION:
    definition: The model equations are represented by all physics equations and material relations according to the RoMM
    models: []
    parent: CUBA.CUDS_COMPONENT
    variables: []
```

where variables is specified but empty?
